language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml

matrix:
  fast_finish: true